# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('python_vote', models.IntegerField(default=0)),
                ('javascript_vote', models.IntegerField(default=0)),
            ],
        ),
    ]
